### PR TITLE
Further IT API simplification

### PR DESCRIPTION
**Pull request by alexeyr**
With this API there is no more need to repeat compilers in each test

### CODE REVIEW

**Comment by alexeyr** [comment]
We can also make `Prog` a type parameter of `ItTestsUtil` instead of a type member. Compilers can be created in early definitions. This should simplify even more.

**Comment by alexeyr** [comment]
Do not merge yet.

**Comment by alexeyr** [comment]
Please review: @aslesarenko @alexanderfilippov @PCMNN

**Comment by alexeyr** [comment]
Another possible change: create test blocks dynamically in functions like `compileSource`/`getStagedOutput`/`compareOutput...`, e.g.

    def compileSource[A, B](f: Prog => Prog#Rep[A => B], functionName: String,
                            compilers: Seq[CompilerWithConfig] = defaultCompilers,
                            graphVizConfig: GraphVizConfig = defaultGraphVizConfig) =
      test(functionName) {
        defaultCompilers.map { cwc =>
          cwc.compiler.buildExecutable(sourceDir(functionName), functionName,
            f(cwc.compiler.scalan).asInstanceOf[cwc.compiler.Exp[A => B]], graphVizConfig)(cwc.config)
        }
      }

Drawback: can't run a single test in IDEA (don't know about SBT).

**Comment by aslesarenko** [comment]
:+1:

**Comment by aslesarenko** [comment]
test block are not problem as long as we can avoid name duplication like this 

`test("name") { compile(theName, f) } `

**Comment by alexeyr** [comment]
Yes, this can be done.

**Pull request merged**
