### PR TITLE
Adding IR for struct types

### PR DESCRIPTION
**Pull request by aslesarenko**
@alexeyr please have a look at how `StructElem.tag` implemented. Do you have better idea how to implement this. `RefinedManifest` is taken from scala-virtualized.

### CODE REVIEW

**Comment by alexeyr** [comment]
1. Why is code used only for LMS interoperation moved into `Elems`?

2. `manifestToTypeTag` doesn't know about `RefinedManifest` (it only uses `manifest.erasure` and `manifest.typeArguments`), so all information about fields is lost there and `RefinedManifest` can be removed. 

3. `StructElem` should contain `Elem[_]`, _not_ `Elem[Any]` and rename `items` to `fields`. It should be handled in `elemToManifest` and only there `RefinedManifest` (one from LMS, not our copy) appears.

**Comment by aslesarenko** [comment]
@alexeyr you forgot to answer my question. :) The reason I ask is exactly because I don't like this implementation. If you have better way I will rewrite before merging and move the Manifest code back to the backend.

**Comment by alexeyr** [comment]
My point in 2 is that I am pretty sure the current implementation always returns `typeTag[Product]`. So a better way to achieve this result is just `val tag = typeTag[Product]` :) If you want a different result, it should be more clear which one.

**Comment by aslesarenko** [comment]
We need to have equality on WeakTypeTag for structs. `typeTag[Product]` doesn't preserve it.

**Comment by alexeyr** [comment]
In which case this implementation doesn't either. Option 1: just override `StructElem.equals` to compare `fields` as well as `tag.tpe`; option 2 (can be done together): add `T: TypeTag` bounds to methods `struct` and `structElem` (and perhaps to `StructTag`). Again, this really depends on what we want to get _and how we want this to be used_. E.g. how do users write structs? E.g. `case class MyStruct(f: Int, g: Array[Foo]) extends Struct` or `new Struct { val f: Int = 1; val g = ... }` or something else?

**Comment by aslesarenko** [comment]
Users will not write structs, at least this is not the goal. Because each `SimpleStruct` will be created at runtime we cannot use implicit TypeTag generation by compiler. So the question is how to generate TypeTag dynamically for any given StructElem?

**Comment by alexeyr** [comment]
> Users will not write structs, at least this is not the goal.  Because each SimpleStruct will be created at runtime

In what circumstances does it happen, then? 

> So the question is how to generate TypeTag dynamically for any given StructElem? 

There is `TypeTag.apply`.

**Comment by alexeyr** [comment]
But as said above, equality of TypeTags themselves shouldn't be necessary; why isn't overriding `StructElem.equals` good enough?

**Comment by aslesarenko** [comment]
I need this structs for generic tuple flattening. JVM code we generate now with `Tuple2` constructions and deconstructions is quite bad in terms of garbage.
If for e1 != e2 it is ok at `CoreBridge` to have e1.tag == e2.tag then I will use `TypeTag[Product]` as approximation.

**Comment by alexeyr** [comment]
> I need this structs for generic tuple flattening. JVM code we generate now with Tuple2 constructions and deconstructions is quite bad in terms of garbage.

For this I do expect users would want to write their own structs instead of dealing with large tuples and `_<n>` methods.

**Comment by aslesarenko** [comment]
This is for auto-flattening phase in compiler, internal IR. DSL front-end is not supposed to change. Users will not see this at all.

**Comment by alexeyr** [comment]
I think it would still be useful to expose, but this may be done later.

**Pull request merged**
