### PR TITLE
Generic bridge

### PR DESCRIPTION
**Pull request by alexeyr**
First part of implementation for #97

### CODE REVIEW

**Comment by alexeyr** [comment]
Not for merge yet.

**Comment by alexeyr** [comment]
Can now be reviewed. @aslesarenko @yzotov @alexanderfilippov

**Comment by aslesarenko** [comment]
:+1:

**Comment by yzotov** [comment]
:+1:

**Comment by alexanderfilippov** [comment]
:ok_hand:

**Pull request merged**
